version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-testdb}
      - DB_USERNAME=${DB_USERNAME:-pguser01}
      - DB_PASSWORD=${DB_PASSWORD:-yoursecurepassword}
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
